//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSRSEmailForm.ReportEmailService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ReportEmailService.IEmailWebService")]
    public interface IEmailWebService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmailWebService/HelloWorld", ReplyAction="http://tempuri.org/IEmailWebService/HelloWorldResponse")]
        string HelloWorld();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmailWebService/HelloWorld", ReplyAction="http://tempuri.org/IEmailWebService/HelloWorldResponse")]
        System.Threading.Tasks.Task<string> HelloWorldAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmailWebService/SendTestEmail", ReplyAction="http://tempuri.org/IEmailWebService/SendTestEmailResponse")]
        string[] SendTestEmail(string to);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmailWebService/SendTestEmail", ReplyAction="http://tempuri.org/IEmailWebService/SendTestEmailResponse")]
        System.Threading.Tasks.Task<string[]> SendTestEmailAsync(string to);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmailWebService/SendEmail", ReplyAction="http://tempuri.org/IEmailWebService/SendEmailResponse")]
        string[] SendEmail(string[] to, string[] cc, string[] bcc, string[] replyTo, string from, string subject, string body, string priority, string[] attachments);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmailWebService/SendEmail", ReplyAction="http://tempuri.org/IEmailWebService/SendEmailResponse")]
        System.Threading.Tasks.Task<string[]> SendEmailAsync(string[] to, string[] cc, string[] bcc, string[] replyTo, string from, string subject, string body, string priority, string[] attachments);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IEmailWebServiceChannel : SSRSEmailForm.ReportEmailService.IEmailWebService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EmailWebServiceClient : System.ServiceModel.ClientBase<SSRSEmailForm.ReportEmailService.IEmailWebService>, SSRSEmailForm.ReportEmailService.IEmailWebService {
        
        public EmailWebServiceClient() {
        }
        
        public EmailWebServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public EmailWebServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EmailWebServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EmailWebServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string HelloWorld() {
            return base.Channel.HelloWorld();
        }
        
        public System.Threading.Tasks.Task<string> HelloWorldAsync() {
            return base.Channel.HelloWorldAsync();
        }
        
        public string[] SendTestEmail(string to) {
            return base.Channel.SendTestEmail(to);
        }
        
        public System.Threading.Tasks.Task<string[]> SendTestEmailAsync(string to) {
            return base.Channel.SendTestEmailAsync(to);
        }
        
        public string[] SendEmail(string[] to, string[] cc, string[] bcc, string[] replyTo, string from, string subject, string body, string priority, string[] attachments) {
            return base.Channel.SendEmail(to, cc, bcc, replyTo, from, subject, body, priority, attachments);
        }
        
        public System.Threading.Tasks.Task<string[]> SendEmailAsync(string[] to, string[] cc, string[] bcc, string[] replyTo, string from, string subject, string body, string priority, string[] attachments) {
            return base.Channel.SendEmailAsync(to, cc, bcc, replyTo, from, subject, body, priority, attachments);
        }
    }
}
